# Generated by Django 2.2.7 on 2019-12-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20191201_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicio',
            new_name='Project',
        ),
    ]
