# Generated by Django 2.2.7 on 2019-12-25 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191211_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 13, 6, 19, 188913, tzinfo=utc), verbose_name='Fecha de edición'),
        ),
    ]
