# Generated by Django 2.2.7 on 2020-03-08 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200217_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 11, 5, 50, 796122, tzinfo=utc), verbose_name='Fecha de edición'),
        ),
    ]
