# Generated by Django 2.2.7 on 2020-03-08 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200308_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 11, 6, 45, 301763, tzinfo=utc), verbose_name='Fecha de edición'),
        ),
    ]
